Hello

# Q2.1

In [1]:
import numpy as np
import scipy
import matplotlib.pyplot as plt
import seaborn as sns
from helpers.iaml01cw2_helpers import *
from templates.iaml01cw2_my_helpers import *
from sklearn.decomposition import PCA
from sklearn.metrics import mean_squared_error
from sklearn import linear_model
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score

DataPath = "zaData"

Xtrn, Ytrn, Xtst, Ytst = load_FashionMNIST(DataPath)

#Step 1
Xtrn_orig = Xtrn
Xtst_orig = Xtst

#Step 2
Xtrn = Xtrn/255.0
Xtst = Xtst/255.0

#Step 3
Xmean = Xtrn.mean(axis=0)

#Step 4
Xtrn_nm = Xtrn - Xmean
Xtst_nm = Xtst - Xmean

lr = linear_model.LogisticRegression().fit(Xtrn_nm, Ytrn)
lr_score = lr.score(Xtst_nm, Ytst)
lr_cm = confusion_matrix(Ytst,lr.predict(Xtst_nm))

def iaml01cw2_q2_1():
    print('test accuracy:', np.round(lr_score,3))
    print('confusion matrix:')
    print(lr_cm)
    
iaml01cw2_q2_1()

D:\Python\Anaconda3\envs\py3iaml\lib\site-packages\sklearn\utils\__init__.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Sequence


test accuracy: 0.84
confusion matrix:
[[819   3  15  50   7   4  90   1  11   0]
 [  5 953   4  27   5   0   3   1   2   0]
 [ 27   4 731  11 133   0  82   2   9   1]
 [ 31  15  14 866  33   0  37   0   4   0]
 [  0   3 115  38 760   2  72   0  10   0]
 [  2   0   0   1   0 911   0  56  10  20]
 [147   3 128  46 108   0 539   0  28   1]
 [  0   0   0   0   0  32   0 936   1  31]
 [  7   1   6  11   3   7  15   5 945   0]
 [  0   0   0   1   0  15   1  42   0 941]]


# Q2.2

In [2]:
svC = svm.SVC().fit(Xtrn_nm, Ytrn)
svC_score = svC.score(Xtst_nm, Ytst)
svC_cm = confusion_matrix(Ytst,svC.predict(Xtst_nm))

def iaml01cw2_q2_2():
    print('test accuracy:',np.round(svC_score,3))
    print('confusion matrix:')
    print(svC_cm)
    
iaml01cw2_q2_2()

test accuracy: 0.846
confusion matrix:
[[845   2   8  51   4   4  72   0  14   0]
 [  4 951   7  31   5   0   1   0   1   0]
 [ 15   2 748  11 137   0  79   0   8   0]
 [ 32   6  12 881  26   0  40   0   3   0]
 [  1   0  98  36 775   0  86   0   4   0]
 [  0   0   0   1   0 914   0  57   2  26]
 [185   1 122  39  95   0 533   0  25   0]
 [  0   0   0   0   0  34   0 925   0  41]
 [  3   1   8   5   2   4  13   4 959   1]
 [  0   0   0   0   0  22   0  47   1 930]]


# Q2.3

In [ ]:
pca_23_2 = PCA(n_components = 2).fit(Xtrn_nm)
trans_23_2 = pca_23_2.fit_transform(Xtrn_nm)
V = pca_23_2.components_
std = np.sqrt(pca_23_2.explained_variance_)

std1 = std[0]
std2 = std[1]
print('std1: ',std1)
print('std2: ',std2)
x1 = np.arange(-5*std1, 5*std1, np.abs(10*std1)/100)
y1 = np.arange(-5*std2, 5*std2, np.abs(10*std2)/100)

x2,y2 = np.meshgrid(x1,y1)

new_grid = np.zeros([10000, 2])

new_grid[:,0] = x2.reshape(1,-1)
new_grid[:,1] = y2.reshape(1,-1)

re_23_2 = pca_23_2.inverse_transform(new_grid)
re_23_2.shape

z = lr.predict(re_23_2).reshape(100,100)

def iaml01cw2_q2_3():
    plt.figure(figsize=(8,6))
    plt.contourf(x2,y2,z, cmap = plt.cm.coolwarm, levels = np.linspace(-0.5,9.5,11))
    plt.xlabel('Standard Deviation for First Principle Component')
    plt.ylabel('Standard Deviation for Second Principle Component')
    plt.title("2.3")

    plt.colorbar().set_ticks(np.linspace(0,9,10))
    
iaml01cw2_q2_3()

# Q2.4

In [ ]:
z2 = svC.predict(re_23_2).reshape(100,100)


def iaml01cw2_q2_4():
    plt.figure(figsize=(8,6))
    plt.contourf(x2,y2,z2, cmap = plt.cm.coolwarm, levels = np.linspace(-0.5,9.5,11))
    plt.xlabel('Standard Deviation for First Principle Component')
    plt.ylabel('Standard Deviation for Second Principle Component')
    plt.title("2.4")

    plt.colorbar().set_ticks(np.linspace(0,9,10))
    
iaml01cw2_q2_4()

# Q2.5

In [ ]:
def find_fir1000(Xtrn_nm, Ytrn, c):
    ar = Xtrn_nm[np.argwhere(Ytrn == c)[:1000]]
    ar = ar.reshape([1000,784])
    return ar

Xsmall = np.concatenate((find_fir1000(Xtrn_nm, Ytrn, 0),
                        find_fir1000(Xtrn_nm, Ytrn, 1),
                        find_fir1000(Xtrn_nm, Ytrn, 2),
                        find_fir1000(Xtrn_nm, Ytrn, 3),
                        find_fir1000(Xtrn_nm, Ytrn, 4),
                        find_fir1000(Xtrn_nm, Ytrn, 5),
                        find_fir1000(Xtrn_nm, Ytrn, 6),
                        find_fir1000(Xtrn_nm, Ytrn, 7),
                        find_fir1000(Xtrn_nm, Ytrn, 8),
                        find_fir1000(Xtrn_nm, Ytrn, 9))
                       )

Ysmall = np.concatenate(( Ytrn[np.argwhere(Ytrn == 0)[:1000].reshape(1000)],
                          Ytrn[np.argwhere(Ytrn == 1)[:1000].reshape(1000)],
                          Ytrn[np.argwhere(Ytrn == 2)[:1000].reshape(1000)],
                          Ytrn[np.argwhere(Ytrn == 3)[:1000].reshape(1000)],
                          Ytrn[np.argwhere(Ytrn == 4)[:1000].reshape(1000)],
                          Ytrn[np.argwhere(Ytrn == 5)[:1000].reshape(1000)],
                          Ytrn[np.argwhere(Ytrn == 6)[:1000].reshape(1000)],
                          Ytrn[np.argwhere(Ytrn == 7)[:1000].reshape(1000)],
                          Ytrn[np.argwhere(Ytrn == 8)[:1000].reshape(1000)],
                          Ytrn[np.argwhere(Ytrn == 9)[:1000].reshape(1000)]
                        ))

var_sp = np.logspace(-2,3,10)

print(var_sp[6])

new = np.array([])
for i in range(10):
    clr_fit = svm.SVC(C = var_sp[i]).fit(Xsmall, Ysmall)
    s = cross_val_score(clr_fit, Xsmall, Ysmall, cv=3, n_jobs=-1)
    s_mean = np.mean(s)
    new = np.append(new, s_mean)

print(new)

other_new = np.array(
    [0.6481958 , 0.69109768, 0.73670227, 0.78380416, 0.81970174,
    0.84470129, 0.85650231, 0.8542039 , 0.8495031 , 0.84060138]
)

def iaml01cw2_q2_5():
    plt.figure(figsize=(8,6))
    plt.scatter(np.log10(var_sp), other_new,label = 'Mean Accuracy', color = 'black')
    plt.plot(np.log10(var_sp), other_new, c = 'red')
    plt.xlabel('Penalty Parameter C')
    plt.ylabel('Mean Cross-Validated Classification Accuracy')
    plt.title('2.5')
    plt.legend(loc = 'lower right')
    plt.grid()
    
iaml01cw2_q2_5()

21.544346900318846


# Q2.6

In [ ]:
def iaml01cw2_q2_6():
    optimal = var_sp[np.argmax(other_new)]

    svc26 = svm.SVC(C = optimal)
    svc_26 = svc26.fit(Xtrn_nm, Ytrn)
    print(svc26.score(Xtrn_nm, Ytrn))
    print(svc26.score(Xtst_nm, Ytst))

iaml01cw2_q2_6()